sudo: required
dist: trusty

services:
- docker

script:
- docker info
- echo "$DOCKER_PASSWORD" | docker login quay.io -u "$DOCKER_USERNAME" --password-stdin
- cd 8
- docker build -t quay.io/woditschka/openjdk:8 .
- docker push quay.io/woditschka/openjdk:8
- cd ..
- cd 10
- docker build -t quay.io/woditschka/openjdk:10 .
- docker push quay.io/woditschka/openjdk:10
- cd ..
- cd 11
- docker build -t quay.io/woditschka/openjdk:11 .
- docker push quay.io/woditschka/openjdk:11-ea
- cd ..
- cd 12
- docker build -t quay.io/woditschka/openjdk:12-ea .
- docker push quay.io/woditschka/openjdk:12-ea
- cd ..

env:
  global:
  - secure: acmOiL1dKUsO+M7hu7RBva1AyVG3RPNi2MH/m40CumiUnYpXVpV0GJsrHIzAEYw42Jx18O7+RdEqSOZ45gw+E96B6ziMMLLAiSWchzs7nDg8DrqhomAuMuDVKUsESX+E3QIyYQDYGVBcmrQIYNgYkQKjdKax9mUf2Fgys7q1d0izFrUObTuMzl+k4aW9igI+cNEz3YeZOcP5QNn9q9vLtZEnqRzrlP0QPEz63KLylrUS/qMsO3rWtUyOOeoDwzwC2mUACbfvRF9gUNnrHr9ERHhfo60CT1x61XQBQY5Xg1lvpnKfR0Qm+Y1HY/gaq6ysGe04LQZ9HkH5eVSAIin1JX++7WQ9cnj8AN+b2+GIkyVKTXmQ51B/pQ2//R40o5hBMVEzGd2DkCaAL93goCSino0K/24kkyLOkHoi7ycv7qk5V7KwfyplloEbomLdiyPOvfy+L5KXuToqv2UcmLoniuEehTYg5IoVVFqg0PgReGxYQwxEbFF5XfqqnXezP0W9u+NImaHDiyen9dMzAM4/b0n0pRgg+fQyk910erk6YHbF/QHtJOMd+qqT2/r5clH4CvBOVGzjE3kcAY1SPjG21NcIJEtRy/3HwZAryjukCy7Jsb4dq0L5/1oozTuevCFNcMgjBpUe/J5OcHU8/5iM1KST3iPZSb3Kk7rUdFzxAvA=
  - secure: AcuEij+FLu9EYKOGDzzzECmQgYgiuGTY0514HqXUMDT/f4NGDKK9dud2+CZAenu0nubkeM/5kwkUeDMXaZX2pauW81A+6+f+0FSCd1oyrrx2qy7ut4V3KVHhb3u5+BXISwJ5yS0+N1WQvPCQPIpvwzLWUdNv3FqxYQ4oyX0pYs6qgxezrT2/4wGPdaL2/IwuxVCX1VsMtqfnFUqxJs6UEbfN9S67XsyC4MDVLUPWENVaocLlP0wisa7GLBKuRbfdlCMdFys5Imq8YgWfQQop3fgUcCUo54nW073kLdb55lJE48dzFV5dj0cx/2YRBg7W+GwBd9Oc9xIzAzeSufFnxLxJG3I5jdhoeEEsC0HWC1LGHPC3It4ErICUj8We0anE8HXtUPLWVpNm9GddnGR/2QIV4RCbLSRjThhXFZaVWelIIgMXOjPwAepxbpWZKiQw0EkUM4Ik98pCQFFYBDcGGiPxPdZ3svLbPuTYmwpiZV1sa7FWa/S/tcG6k+R2+S7iuCWamXnJdrBs7M/U3nB4KPs8xkLqyDCT4ZlnIhwkyRWImxZEiL+CAVtZFi5yIJI52wABxM1DZFq9Ya+7zi4b33ACYtODmGJNpsqYGoH1VKQDI0u4gGuk/ga9c4gCia2bBniU49Anyo0z23I0YqEZbiHo4Tt0K/pnripPk+Z7tEs=
